services:
  - type: web
    plan: free
    name: cp2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/dreamloves/cp2.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMIN
        sync: false
